### ISSUE TITLE
How to generate a CHANGELOG file and prepend changes to it?

### ISSUE THREAD

**Issue by sadok-f** [go-semantic-release/changelog-generator-default#5]
Hello,
Thank you for the great tool!
in my `.semrelrc` file, I've added this section:
```json
 "changelog-generator": {
      "name": "default",
      "options": {
        "emojis": "true"
      }
    },
```
but it seems it is adding the changelog to the release note, 
How can I append the generated changelog to a CHANGELOG file within the pipeline (Gitlab)?
I used the node Semantic-release library before and it was a simple configuration to add to `.releaserc` file like :
```json
[
   "@semantic-release/changelog",
   {
      "changelogFile": "CHANGELOG.md",
      "changelogTitle": "# Project Changelog"
   }
],
```

Thank you!

**Comment by christophwitzko** [comment]
Hey @sadok-f, thank you ☺️ 

This currently works by setting the following CLI flags: `--changelog CHANGELOG.md --prepend-changelog`. Then semantic-release will add the latest release notes to the beginning of the `CHANGELOG.md` file.
While writing this, I am just realizing that it would make sense to add these options to the `.semrelrc` config file, so all the config is in one place. 👍 

Btw. you wrote in your issue that you want to "append the generated changelog". Would you prefer this over prepending?

Best,
Chris

**Comment by sadok-f** [comment]
Thank you @christophwitzko for your response.
Actually I want to prepending to an exiting Changelog file, I'll fix the typo in the issue title.

I just tried the CLI flags, the job succeeded but I don't see any changes to Changelog.md file
here the full output:
```
$ ./semantic-release --hooks goreleaser --changelog CHANGELOG.md --prepend-changelog
[go-semantic-release]: version: 2.27.1
[go-semantic-release]: trying to prefetch plugins...
[go-semantic-release]: all plugins were prefetched!
[go-semantic-release]: ci-condition plugin: GitLab CI@1.8.0
[go-semantic-release]: provider plugin: GitLab@1.12.1
[go-semantic-release]: getting default branch...
[go-semantic-release]: found default branch: main
[go-semantic-release]: repo is private
[go-semantic-release]: found current branch: main
[go-semantic-release]: found current sha: fbe46b12ea43ac1631ffb078c57b920541cbab3e
[go-semantic-release]: hooks plugins: GoReleaser@1.6.0
[go-semantic-release]: running CI condition...
[go-semantic-release]: getting latest release...
[go-semantic-release]: found version: 1.0.1
[go-semantic-release]: getting commits...
[go-semantic-release]: analyzing commits...
[go-semantic-release]: commit-analyzer plugin: default@1.11.0
[go-semantic-release]: calculating new version...
[go-semantic-release]: new version: 1.0.2
[go-semantic-release]: generating changelog...
[go-semantic-release]: changelog-generator plugin: default@1.12.1
[go-semantic-release]: creating release...
[go-semantic-release]: warning: file update plugins found but no files marked for update. You may be missing the update flag, e.g. --update package.json
[hooks-goreleaser]:   • loading config file                              file=.goreleaser.yml
[hooks-goreleaser]:   • build parallelism is set to 30
[hooks-goreleaser]:   • loading environment variables
[hooks-goreleaser]:     • using token from "$GITLAB_TOKEN"
[hooks-goreleaser]:   • skipping git pipe
[hooks-goreleaser]:   • parsing tag
[hooks-goreleaser]:   • setting defaults
[hooks-goreleaser]:       • DEPRECATED: `archives.rlcp` will be the default soon, check https://goreleaser.com/deprecations#archivesrlcp for more info
[hooks-goreleaser]:   • checking distribution directory
[hooks-goreleaser]:   • loading go mod information
[hooks-goreleaser]:     • took: 1s
[hooks-goreleaser]:   • build prerequisites
[hooks-goreleaser]:   • writing effective config file
[hooks-goreleaser]:     • writing                                        config=dist/config.yaml
[hooks-goreleaser]:   • building binaries
[hooks-goreleaser]:     • building                                       binary=dist/tools/mytool-cli_linux_amd64_v1/mytool-cli
[hooks-goreleaser]:     • took: 38s
[hooks-goreleaser]:   • archives
[hooks-goreleaser]:     • creating                                       archive=dist/mytool-cli-1.0.2-windows-amd64.zip
[hooks-goreleaser]:     • took: 1s
[hooks-goreleaser]:   • publishing
[hooks-goreleaser]:     • scm releases
[hooks-goreleaser]:       • creating or updating release                 repo= tag=v1.0.2
[hooks-goreleaser]:       • release updated                              name=v1.0.2
[hooks-goreleaser]:       • uploading to release                         file=dist/mytool-cli-1.0.2-darwin-amd64.zip name=mytool-cli-1.0.2-darwin-amd64.zipp
[hooks-goreleaser]:       • published                                    url=https://gitlab.internal.local/mytool-cli/-/releases/v1.0.2
[hooks-goreleaser]:       • took: 2s
[hooks-goreleaser]:   • took: 2s
[hooks-goreleaser]:   • storing release metadata
[hooks-goreleaser]:     • writing                                        file=dist/artifacts.json
[hooks-goreleaser]:     • writing                                        file=dist/metadata.json
[hooks-goreleaser]:   • announcing
[go-semantic-release]: done.
[go-semantic-release]: stopping plugins...
```

My .goreleaser.yml:
```yml
builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
    main: ./
    binary: mytool-cli
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -extldflags '-static'
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commitSHA={{.FullCommit}}
      - -X main.buildDate={{.Date}}

checksum:
  disable: true

archives:
  - id: w/version
    name_template: "mytool-cli-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: false
    format: zip
    files:
      - none*

gitlab_urls:
  api: https://gitlab.internal.local/api/v4/
  download:  https://gitlab.internal.local
  use_package_registry: false
```


.semrelrc file:
```json
{
  "plugins": {
    "commit-analyzer": {
      "name": "default@^1.0.0"
    },
    "ci-condition": {
      "name": "gitlab"
    },
    "changelog-generator": {
      "name": "default",
      "options": {
        "emojis": "true"
      }
    },
    "provider": {
      "name": "gitlab",
      "options": {
        "gitlab_projectid": "32044"
      }
    }
  }
}
```
